//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    /// <summary>
    /// EF上下文
    /// </summary>
    public partial class wkmvc_dbEntities : DbContext
    {
        public wkmvc_dbEntities()
            : base("name=wkmvc_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        /// <summary>
        /// SYS_USER 实体
        /// </summary>
        public virtual DbSet<SYS_USER> SYS_USER { get; set; }
    }
}
